# Site settings
title: The Stack
email: online@media.ucla.edu
description: > # this means to ignore newlines until "baseurl:"
  The Stack is Daily Bruin’s data journalism and newsroom tech blog. We investigate
  public data, discuss our experiments with technology and apply quantitative
  insights to real life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stack.dailybruin.com" # the base hostname & protocol for your site
twitter_username: _thestack
github_username:  daily-bruin

# Outputting
permalink: pretty # don't have `.html` on the end of permalinks
timezone: America/Los_Angeles

# Build settings
markdown: kramdown
