name: Scheduled python
on:
  schedule:
  - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1.0.0
        with:
          ref: refs/heads/master
      - name: Setup Python
        uses: actions/setup-python@v1.2.0
      - name: Run python
        run: python python/posts/corona-hospitals/map-scraping.py
      - name: Test
        run: touch test.txt
      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "ci: Automated build push" -a | exit 0
      - name: Push changes
        if: github.ref == 'refs/heads/covid-hospitals'
        uses: ad-m/github-push-action@covid-hospitals
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Trigger our build webhook on Netlify
        run: curl -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.CRON_BUILD_HOOK_HOSPITALBRANCH }}
